### ISSUE TITLE
sync_time

### ISSUE THREAD

**Issue by valensc** [weiyhcarlos/trainning#1]
## code/syn_time.py
1. subprocess滥用，python有自己的ntp库，不需要依赖ntpdate。
2. 尽量不要上传二进制文件，尤其是在code目录。
3. 直接装自带的deb包并使用ntpdate校准系统时间，可能引发一系列问题，例如：
   
   ＊ 兼容性
   ＊ 被监控机有自己需要同步的ntp服务器，并且业务服务强依赖该ntp，监控agent应该尽量避免修改任何系统环境

**Comment by dongfengpo0813** [comment]
@valensc 
之前没有了解到ntplib.
现在已经更正.
