### ISSUE TITLE
代码规范

### ISSUE THREAD

**Issue by valensc** [weiyhcarlos/trainning#2]
注意以下问题：
1. 单行代码79字符，包括注释
2. 使用常用且易理解的缩写 _args_par.py_,
3. 变量命名尽量有意义  _args_par.py line18 dic_
4. 使用log而非print
5. 尽量避免使用保留字和buildin函数名作为变量名
6. 仍有不少配置hardcode在代码里
7. 使用统一命名规范： global_vars， varDict

**Comment by dongfengpo0813** [comment]
@valensc

已修改
